# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow integrates njsscan with GitHub's Code Scanning feature
# nodejsscan is a static security code scanner that finds insecure code patterns in your Node.js applications

name: CI ➟ Security ➟ NJS Scan SARIF

on:
  push:
    branches: [ "feat-ci-cd-security" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "feat-ci-cd-security" ]
  #schedule:
  #  - cron: '22 20 * * 3'

permissions:
  contents: read

jobs:
  njs-scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    name: NJS Scan code
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Scan the code
      id: njsscan
      uses: ajinabraham/njsscan-action@master
      with:
        args: '.'
        #args: '. --sarif --output results.sarif || true'
    #- name: Upload report
    #  uses: github/codeql-action/upload-sarif@v2
    #  with:
    #    sarif_file: results.sarif
